### ISSUE TITLE
Selection text for dynamic dropdown

### ISSUE THREAD

**Issue by torosm** [torosm/UI-UX#1]
Make sure it only behaves on the selected dropdown element. It currently affect all the dropdown element in the page. Make sure its reusable to other dropdowns if needed by assigning class.

**Comment by khanujasunny** [comment]
I have tested my last commit with multiple screen-size and it seems to work fine.
Please check : https://www.youtube.com/watch?v=8l9SegEJFm4&feature=youtu.be

**Comment by torosm** [comment]
"Added classname : updateItemText" looks good your suggestion for a refresh button in the remote content is a better solution and more pragmatic. Will just to make it work with a split button.
"|item 1|refresh icon|caret|".   Feel free to implement these in the child content.

**Comment by khanujasunny** [comment]
Hi Mike,
By your above comment you mean to change : 
<button attributes>Item Text  <span class="caret"></span></button>
to : 
<button attributes class="check">Item Text | refresh|caret </button>

Please confirm

**Comment by torosm** [comment]
Yup. keep in mind that the "Item Text" can all just be a text element or a button.  But, definitely the "Refresh" and "Caret" will be a Button.

**Comment by torosm** [comment]
Irrelevant now. Sunny K. to open similar issue
