### ISSUE TITLE
add new data-attribute to "addTab coajaxify"

### ISSUE THREAD

**Issue by torosm** [torosm/UI-UX#4]
Hi Sunny,

Can you make the addNewTab refresh and close option/button as an data tab attribute.
For example:
1. data-button= refresh, close (display both buttons)
2. data-button= close (display close button only),

**Comment by khanujasunny** [comment]
Functionality implemented

**Comment by torosm** [comment]
I just quickly went trought it but it seems the refresh button dont work.

**Comment by torosm** [comment]
refresh button is working. it wasn’t noticeable in FF.

**Comment by torosm** [comment]
I will reopen this. The issue is:

1. If the data button attribute has only one item the remote content wont load. for instance, data-button="close". Please see the gh-page in browser and click any side menu item.

**Comment by khanujasunny** [comment]
Fixed
