### ISSUE TITLE
Refresh button inside dynamic view container tab

### ISSUE THREAD

**Issue by khanujasunny** [torosm/UI-UX#7]
Clicking refresh button inside dynamic view (loaded from url) should refresh that tab:
http://i.imgur.com/kzaIkdG.jpg

**Comment by khanujasunny** [comment]
Fixed

**Comment by torosm** [comment]
HI Sunny.

So far when clicking the reload button. The content dont load and only showing "Loading...". Tested in Chrome and FireFox

**Comment by torosm** [comment]
BTW. It behaves in the "staticTab:RemoteContent" tab.

**Comment by khanujasunny** [comment]
Please check screen-cast of above said issue:
https://youtu.be/T7T-S6wWDnA

**Comment by torosm** [comment]
Yes it is functional on a non static tab but not in static tab clicked the tab "staticTab:RemoteContent" and try to reload contents

**Comment by khanujasunny** [comment]
Fixed
