### ISSUE TITLE
Refresh button in select box which have cojaxify link

### ISSUE THREAD

**Issue by khanujasunny** [torosm/UI-UX#8]

**Comment by torosm** [comment]
BTW. Is it possible to have the "ViewA1" as text (span or div or heading, etc) instead of a button with no style? What Im saying is can we make that element independent. That way it can be place anywhere in the page for any future arrangement. thanks

**Comment by khanujasunny** [comment]
Mike,
Requirement is bit unclear to me, let me breakdown and try to understand

1. "View A1" as text(span or div) : Yes, its text right now under a span tag
2. inside of a button: Yes, currenty its inside a button tag only
http://i.imgur.com/m5PMXsI.jpg

3: With no style: There is no style added , instead we have a class to remove style:
http://i.imgur.com/s3Wdi4K.jpg
4. Can we make it independent: yes it can be placed anywhere inside application where we have similar use case and shares same stylesheet & systemapp.js

**Comment by torosm** [comment]
reload button with class "reloadSelectedUrl" does not work on initial load
